<?php

namespace Database\Seeders\Misc;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountriesSeeder extends Seeder
{
    public function run()
    {
        $countries = [
            ['name' => 'United Kingdom', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Germany', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'United States', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Afghanistan', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Albania', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Algeria', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Andorra', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Angola', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Antigua and Barbuda', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Argentina', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Armenia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Australia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Austria', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Azerbaijan', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Bahamas, The', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Bahrain', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Bangladesh', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Barbados', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Belarus', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Belgium', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Belize', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Benin', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Bhutan', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Bolivia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Bosnia and Herzegovina', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Botswana', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Brazil', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Brunei', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Bulgaria', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Burkina Faso', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Burma', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Burundi', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Cambodia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Cameroon', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Canada', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Cape Verde', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Central African Republic', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Chad', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Chile', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'China', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Colombia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Comoros', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Congo (Brazzaville)', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Congo (Kinshasa)', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Costa Rica', 'stripe_enabled' => true, 'active' => true],
            ['name' => "Cote d'Ivoire", 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Croatia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Cuba', 'stripe_enabled' => false, 'active' => true],
            ['name' => 'Cyprus', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Czech Republic', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Denmark', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Djibouti', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Dominica', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Dominican Republic', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Ecuador', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Egypt', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'El Salvador', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Equatorial Guinea', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Eritrea', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Estonia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Ethiopia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Fiji', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Finland', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'France', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Gabon', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Gambia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Georgia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Ghana', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Greece', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Grenada', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Guatemala', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Guinea', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Guinea-Bissau', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Guyana', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Haiti', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Honduras', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Hungary', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Iceland', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'India', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Indonesia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Iran', 'stripe_enabled' => false, 'active' => true],
            ['name' => 'Iraq', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Ireland', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Israel', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Italy', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Jamaica', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Japan', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Jordan', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Kazakhstan', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Kenya', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Kiribati', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Korea, North', 'stripe_enabled' => false, 'active' => true],
            ['name' => 'Korea, South', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Kosovo', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Kuwait', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Kyrgyzstan', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Laos', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Latvia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Lebanon', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Lesotho', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Liberia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Libya', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Liechtenstein', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Lithuania', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Luxembourg', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Madagascar', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Malawi', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Malaysia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Maldives', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Mali', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Malta', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Marshall Islands', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Mauritania', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Mauritius', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Mexico', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Micronesia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Moldova', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Monaco', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Mongolia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Montenegro', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Morocco', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Mozambique', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Namibia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Nauru', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Nepal', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Netherlands', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'New Zealand', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Nicaragua', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Niger', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Nigeria', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'North Macedonia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Norway', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Oman', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Pakistan', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Palau', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Panama', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Papua New Guinea', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Paraguay', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Peru', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Philippines', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Poland', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Portugal', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Qatar', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Romania', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Russia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Rwanda', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Saint Kitts and Nevis', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Saint Lucia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Saint Vincent and the Grenadines', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Samoa', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'San Marino', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Sao Tome and Principe', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Saudi Arabia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Senegal', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Serbia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Seychelles', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Sierra Leone', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Singapore', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Slovakia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Slovenia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Solomon Islands', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Somalia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'South Africa', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'South Sudan', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Spain', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Sri Lanka', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Sudan', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Suriname', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Sweden', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Switzerland', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Syria', 'stripe_enabled' => false, 'active' => true],
            ['name' => 'Taiwan', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Tajikistan', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Tanzania', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Thailand', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Timor-Leste', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Togo', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Tonga', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Trinidad and Tobago', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Tunisia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Turkey', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Turkmenistan', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Tuvalu', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Uganda', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Ukraine', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'United Arab Emirates', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Uruguay', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Uzbekistan', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Vanuatu', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Vatican City', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Venezuela', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Vietnam', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Yemen', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Zambia', 'stripe_enabled' => true, 'active' => true],
            ['name' => 'Zimbabwe', 'stripe_enabled' => true, 'active' => true],
        ];

        // Insert the countries into the database
        Country::insert($countries);
    }
}
